import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const dataEvidencia = new Date("2026-09-05T00:00:00.000Z");
const contatos = [
  ["contato-sirio-matheus-martins", "Matheus Martins dos Anjos", "Comprador sênior", "Compras", "https://br.linkedin.com/in/matheus-martins-dos-anjos-191ab8150", "org-627ee072", "Comprador sênior identificado em publicação pública relacionada ao Hospital Sírio-Libanês."],
  ["contato-sirio-eduardo-ambrosio", "Eduardo Ambrósio", "Profissional de compras", "Compras e Facilities", "https://br.linkedin.com/in/eduardo-ambrosio-7209619", "org-627ee072", "Perfil público associado ao Hospital Sírio-Libanês e a processos de compras de obras, manutenção, serviços e facilities."],
  ["contato-sirio-thiago-otoni", "Thiago Otoni", "Coordenador de Compras", "Compras", "https://br.linkedin.com/in/thiago-otoni-98873364", "org-627ee072", "Perfil público identifica coordenação de Compras no Hospital Sírio-Libanês."],
  ["contato-rededor-rafael-almeida", "Rafael Almeida", "Profissional de Gestão de Compras", "Compras", "https://br.linkedin.com/in/rafael-almeida-1641a168", "org-d753d961", "Perfil público associado à Rede D’Or São Luiz e a atividades de gestão de compras."],
  ["contato-cema-domenico-forte", "Domenico Rodolfo Forte", "Gestor administrativo e operacional", "Facilities e Operações", "https://br.linkedin.com/in/domenico-rodolfo-forte-a40b866a", "org-22379759", "Perfil público associado ao CEMA Hospital Especializado, com experiência em gestão administrativa, operacional e facilities."],
  ["contato-santacatarina-evelin-rodrigues", "Evelin Rodrigues", "Profissional de Compras", "Compras", "https://br.linkedin.com/in/evelin-rodrigues-5b94931b5", "org-isol-inst-cnes-2688603", "Perfil público associado ao Hospital Santa Catarina - Paulista e à área de compras."],
  ["contato-premium-care-graziela-moreto", "Graziela Moreto", "Gerente / Administrador", "Administração", "https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3550306032699", "org-7d8f25e8", "Ficha pública do CNES identifica Graziela Moreto como Gerente / Administrador da CLINICA PREMIUM CARE SAUDE LTDA."],
  ["contato-cma-andre-pla", "André Mortari Plá", "Administrador", "Administração", "https://datamercantil.com.br/wp-content/uploads/2026/06/DATA-MERCANTIL-20-21-E-22.06.26-IMPRESSO.pdf", "org-isol-inst-cnes-3876500", "Edital público de junho de 2026 identifica André Mortari Plá como administrador da CMA - SERVICOS MEDICOS HOSPITALARES LTDA."],
  ["contato-cma-saullo-silveira", "Saullo Queiroz Silveira", "Administrador", "Administração", "https://datamercantil.com.br/wp-content/uploads/2026/06/DATA-MERCANTIL-20-21-E-22.06.26-IMPRESSO.pdf", "org-isol-inst-cnes-3876500", "Edital público de junho de 2026 identifica Saullo Queiroz Silveira como administrador da CMA - SERVICOS MEDICOS HOSPITALARES LTDA."],
  ["contato-cma-rodrigo-constantino", "Rodrigo Giovanelli Constantino", "Administrador", "Administração", "https://datamercantil.com.br/wp-content/uploads/2026/06/DATA-MERCANTIL-20-21-E-22.06.26-IMPRESSO.pdf", "org-isol-inst-cnes-3876500", "Edital público de junho de 2026 identifica Rodrigo Giovanelli Constantino como administrador da CMA - SERVICOS MEDICOS HOSPITALARES LTDA."],
  ["contato-day-hospital-antonio-mellace", "Antonio Fernandes Mellace", "Sócio-administrador", "Administração", "https://casadosdados.com.br/solucao/cnpj/day-hospital-de-ermelino-matarazzo-ltda-67133637000127", "org-isol-inst-cnes-2078627", "Cadastro público identifica Antonio Fernandes Mellace como sócio-administrador do DAY HOSPITAL DE ERMELINO MATARAZZO LTDA."],
  ["contato-day-hospital-gilberto-mellace", "Gilberto Maida Mellace Junior", "Sócio-administrador", "Administração", "https://casadosdados.com.br/solucao/cnpj/day-hospital-de-ermelino-matarazzo-ltda-67133637000127", "org-isol-inst-cnes-2078627", "Cadastro público identifica Gilberto Maida Mellace Junior como sócio-administrador do DAY HOSPITAL DE ERMELINO MATARAZZO LTDA."],
  ["contato-day-hospital-carlos-mellace", "Carlos Alberto Fernandes Mellace", "Sócio-administrador", "Administração", "https://casadosdados.com.br/solucao/cnpj/day-hospital-de-ermelino-matarazzo-ltda-67133637000127", "org-isol-inst-cnes-2078627", "Cadastro público identifica Carlos Alberto Fernandes Mellace como sócio-administrador do DAY HOSPITAL DE ERMELINO MATARAZZO LTDA."],
  ["contato-acc-celso-oliveira", "Celso Marques de Oliveira", "Diretor", "Administração", "https://portaldatransparencia.gov.br/convenios/767366/pessoa-juridica/60961968000106-fundacao-antonio-prudente", "org-isol-inst-cnes-7060165", "Portal da Transparência identifica Celso Marques de Oliveira como diretor da FUNDACAO ANTONIO PRUDENTE."],
  ["contato-acc-liana-moraes", "Liana Maria Carraro de Moraes", "Diretora", "Administração", "https://portaldatransparencia.gov.br/convenios/767366/pessoa-juridica/60961968000106-fundacao-antonio-prudente", "org-isol-inst-cnes-7060165", "Portal da Transparência identifica Liana Maria Carraro de Moraes como diretora da FUNDACAO ANTONIO PRUDENTE."],
  ["contato-acc-ademar-lopes", "Ademar Lopes", "Diretor", "Administração", "https://portaldatransparencia.gov.br/convenios/767366/pessoa-juridica/60961968000106-fundacao-antonio-prudente", "org-isol-inst-cnes-7060165", "Portal da Transparência identifica Ademar Lopes como diretor da FUNDACAO ANTONIO PRUDENTE."],
  ["contato-acc-jose-curado", "Jose Hermilio Curado", "Diretor", "Administração", "https://portaldatransparencia.gov.br/convenios/767366/pessoa-juridica/60961968000106-fundacao-antonio-prudente", "org-isol-inst-cnes-7060165", "Portal da Transparência identifica Jose Hermilio Curado como diretor da FUNDACAO ANTONIO PRUDENTE."],
  ["contato-haoc-leonisa-obrusnik", "Leonisa Scholz Obrusnik", "Diretora da Cadeia de Suprimentos", "Suprimentos", "https://codigo-healthtech.bionexo.com/quando-a-visao-o-calor-humano-e-a-paixao-comandam-a-area-de-suprimentos-todo-o-setor-ganha-inclusive-o-paciente", "org-aa1f20b8", "Publicação profissional identifica Leonisa Scholz Obrusnik na liderança da cadeia de suprimentos do Hospital Alemão Oswaldo Cruz."],
  ["contato-haoc-caique-felisbino", "Caique Eduardo de Araújo Felisbino", "Assistente Administrativo", "Administração", "https://hospitais.proadi-sus.org.br/projeto/haoc/teleconsulta-diabetes", "org-aa1f20b8", "Página pública do projeto PROADI-SUS identifica Caique Eduardo de Araújo Felisbino como Assistente Administrativo do Hospital Alemão Oswaldo Cruz."],
  ["contato-alvorada-osvaldo-pires", "Osvaldo Guilherme Nunes Pires", "Gerente / Administrador", "Administração", "https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3550300266167", "org-isol-inst-cnes-266167", "Ficha pública do CNES identifica Osvaldo Guilherme Nunes Pires como Gerente / Administrador do Hospital Alvorada Taguatinga S.A."],
  ["contato-hospital-pele-adrielle-monteiro", "Adrielle Monteiro", "Assistente Administrativo", "Administração", "https://www.econodata.com.br/consulta-empresa/15479898000108-hospital-da-pele-ltda", "org-isol-inst-cnes-9646019", "Organograma público identifica Adrielle Monteiro como Assistente Administrativo da Hospital da Pele."],
] as const;

async function main() {
  for (const [id, nome, cargo, area, linkedinUrl, grupoEconomicoId, observacao] of contatos) {
    const grupo = await prisma.grupoEconomico.findFirst({ where: { id: grupoEconomicoId, tipoDado: { not: "DEMONSTRACAO" } }, select: { id: true, nome: true } });
    if (!grupo) throw new Error(`Grupo não encontrado ou demonstrativo: ${grupoEconomicoId}`);
    const fonteId = `fonte-publica-${id}`;
    await prisma.fonte.upsert({ where: { id: fonteId }, update: { nome: `Perfil público de ${nome} no LinkedIn`, url: linkedinUrl, tipoDado: "FATO_PUBLICO" }, create: { id: fonteId, nome: `Perfil público de ${nome} no LinkedIn`, url: linkedinUrl, tipoDado: "FATO_PUBLICO" } });
    await prisma.contatoProfissional.upsert({ where: { id }, update: { nome, cargo, area, empresa: grupo.nome, linkedinUrl, papelComercial: "INFLUENCIADOR", tipoPapelComercial: "INFERENCIA", tipoDado: "FATO_PUBLICO", confianca: "ALTA", statusRevisao: "APROVADA", ativo: true, fonteId, dataEvidencia, observacao, grupoEconomicoId: grupo.id }, create: { id, nome, cargo, area, empresa: grupo.nome, linkedinUrl, papelComercial: "INFLUENCIADOR", tipoPapelComercial: "INFERENCIA", tipoDado: "FATO_PUBLICO", confianca: "ALTA", statusRevisao: "APROVADA", ativo: true, fonteId, dataEvidencia, observacao, grupoEconomicoId: grupo.id } });
  }
  console.log(`Lote 1 persistido: ${contatos.length} contatos públicos auditáveis.`);
}

main().catch((erro) => { console.error(erro); process.exitCode = 1; }).finally(() => prisma.$disconnect());
