import { NivelConfianca, PrismaClient, StatusPesquisaContato, StatusRevisao } from "@prisma/client";

const prisma = new PrismaClient();

type Pesquisa = {
  grupoEconomicoId: string;
  dataPesquisa: string;
  termosConsulta: string[];
  fontesConsultadas: string[];
  resultado: string;
  confianca: NivelConfianca;
  status: StatusPesquisaContato;
  statusRevisao: StatusRevisao;
};

const pesquisas: Pesquisa[] = [
  {
    grupoEconomicoId: "org-isol-inst-cnes-4065255",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: [
      "AC MATHIAS CENTRO DE ODONTOLOGIA E DIAGNOSTICO POR IMAGEM compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes",
      "AC Mathias compras",
      "AC Mathias LinkedIn",
    ],
    fontesConsultadas: ["https://br.linkedin.com/in/guilherme-pereira-4290b7251"],
    resultado: "Nenhum contato foi aceito: o perfil pÃºblico associado Ã  organizaÃ§Ã£o nÃ£o expÃµe conjuntamente vÃ­nculo corporativo atual e cargo-alvo verificÃ¡vel.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-6307647",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ACALANTO CLINICA MULTIDISCIPLINAR LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Ind_Unidade_Listar.asp?VComp=201702&VEstado=35&VListar=1&VMun=&VSubUni=&VTipo=36", "https://www.seu-convenio.com/prestador/acalanto-clinica-multidisciplinar-10592719000201"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas verificadas identificam a organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa, vÃ­nculo corporativo atual e cargo-alvo conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3919072",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ACEBRAS SERVICOS MEDICOS HOSPITALARES LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://www.escavador.com/diarios/5748076/TRF3/diario-de-justica-eletronico-nacional-%28djen%29/2023-06-06?page=623"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica confirma contexto empresarial, sem pessoa vinculada em cargo-alvo corporativo verificÃ¡vel.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2890941",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["AJ SERVICOS MEDICOS HOSPITALARES LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://www.tce.sp.gov.br/sites/default/files/portal/03___TC_024143_989_24_2___Relatorio_DCG___Hospitais_Portas_Abertas_Ocultado.pdf", "https://brazilguide.net/c/aj-servicos-medicos-hospitalares-ltda-44842785000115"],
    resultado: "Nenhum contato profissional foi aceito: as fontes pÃºblicas confirmam a organizaÃ§Ã£o e uma central publicada, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual inequÃ­vocos.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-452947",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ALMEIDA ALMEIDA CLINICA CAPILAR LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://bula.com.br/index.php/estabelecimento/hospital-do-cabelo-0452947"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento, sem pessoa, cargo-alvo corporativo e vÃ­nculo atual demonstrados conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4281829",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ALTA SAUDE HOSPITALAR ESPECIALIDADES MEDICAS LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://hgp.spdmafiliadas.org.br/wp-content/uploads/sites/13/2026/01/Relacao-Prestadores-de-Servicos-Pessoa-Juridica-2025.pdf", "https://cnes2.datasus.gov.br/Lista_Es_Municipio.asp?NomeEstado=sao_paulo&VCodMunicipio=355030&VEstado=35"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam a organizaÃ§Ã£o e sua prestaÃ§Ã£o de serviÃ§os, sem pessoa em cargo-alvo corporativo com vÃ­nculo atual verificÃ¡vel.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-59c7d05d",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["AMICO SAUDE LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://diariooficial.imprensaoficial.com.br/doflash/prototipo/2021/Abril/16/empresarial/pdf/pg_0069.pdf", "https://impresso.monitormercantil.com.br/wp-content/uploads/2026/05/MM-13_05_2026.pdf"],
    resultado: "Nenhum contato foi aceito: as publicaÃ§Ãµes corporativas verificadas nÃ£o expÃµem pessoa com cargo-alvo e vÃ­nculo atual inequÃ­vocos.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-1090682",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["AMMIMED SERVICOS MEDICOS HOSP LABOR LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://cnpj.biz/48567235000196"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a organizaÃ§Ã£o, sem pessoa, cargo-alvo corporativo e vÃ­nculo atual demonstrados conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4490193",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["AMMIMED SERVICOS MEDICOS HOSPITALARES E LABORATORIAIS LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3550304490193"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento, sem pessoa, cargo-alvo corporativo e vÃ­nculo atual demonstrados conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-8122768",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["AMP MEDICINA HOSPITALAR LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/amp-medicina-hospitalar-ltda-57036414000198"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a organizaÃ§Ã£o, sem pessoa, cargo-alvo corporativo e vÃ­nculo atual demonstrados conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-9085149",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ANALIA FRANCO DAY HOSPITAL DE CIRUGIA PLASTICA LTDA ME compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3550309085149"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica expÃµe direÃ§Ã£o clÃ­nica, cargo assistencial fora dos alvos comerciais definidos, e nÃ£o comprova responsÃ¡vel corporativo de Compras, Suprimentos, OperaÃ§Ãµes, AdministraÃ§Ã£o ou equivalente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4504003",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ANEXTESIA CLINICA DE ANESTESIA E SERVICOS MEDICOS HOSPITALAR compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: [],
    resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4893549",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ANIS GHATTAS MITRI FILHO CIA LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://ishaoc.org.br/contratacoes-encerradas/", "https://adm.cejam.org.br/storage/transparencias_docs/912d6400-1418-11f1-96d9-2d064efad5f6.pdf"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam a pessoa jurÃ­dica em contrataÃ§Ãµes, sem pessoa em cargo-alvo corporativo e vÃ­nculo atual verificÃ¡vel.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4838696",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["AR MEDICINA HOSPITALAR LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: [],
    resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4554507",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ARQUI SERVICOS MEDICOS HOSPITALARES LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/arqui-servicos-medicos-hospitalares-ltda-49860823000186"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a organizaÃ§Ã£o e dados cadastrais, sem pessoa em cargo-alvo corporativo com vÃ­nculo atual verificÃ¡vel.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-5957397",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASCLEPIOS SERVICOS MEDICOS HOSPITALARES LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://www.seu-convenio.com/prestador/asclepios-servicos-medicos-hospitalares-60301185000104"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento, sem pessoa, cargo-alvo corporativo e vÃ­nculo atual demonstrados conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-7469926",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSISTENCIA CIRURGICA CLINIS LTDA compras OR suprimentos OR administraÃ§Ã£o OR operaÃ§Ãµes OR facilities"],
    fontesConsultadas: ["https://diariooficial.imprensaoficial.com.br/doflash/prototipo/2020/Janeiro/22/exec1/pdf/pg_0031.pdf"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica menciona a pessoa jurÃ­dica sem expor pessoa em cargo-alvo corporativo e vÃ­nculo atual verificÃ¡vel.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2076934",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSOCIACAO BENEFICENTE DOS HOSPITAIS SOROCABANA (compras OR suprimentos OR strategic sourcing OR facilities OR operaÃ§Ãµes OR administraÃ§Ã£o OR contratos OR expansÃ£o OR RH OR benefÃ­cios OR mobilidade OR supply chain)", "site:linkedin.com/in ASSOCIACAO BENEFICENTE DOS HOSPITAIS SOROCABANA compras OR suprimentos OR administrativo"],
    fontesConsultadas: [],
    resultado: "Nenhum contato foi aceito: as consultas pÃºblicas nÃ£o retornaram perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-a3148459",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSOCIACAO BENEFICENTE SIRIA (compras OR suprimentos OR strategic sourcing OR facilities OR operaÃ§Ãµes OR administraÃ§Ã£o OR contratos OR expansÃ£o OR RH OR benefÃ­cios OR mobilidade OR supply chain)", "site:linkedin.com/in ASSOCIACAO BENEFICENTE SIRIA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://br.linkedin.com/in/juliana-caetano-neres-315824199"],
    resultado: "Nenhum contato foi aceito: o perfil pÃºblico associado Ã  organizaÃ§Ã£o nÃ£o expÃµe cargo-alvo corporativo atual de forma verificÃ¡vel.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4232925",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSOCIACAO CONGREGACAO DE SANTA CATARINA (compras OR suprimentos OR strategic sourcing OR facilities OR operaÃ§Ãµes OR administraÃ§Ã£o OR contratos OR expansÃ£o OR RH OR benefÃ­cios OR mobilidade OR supply chain)", "site:linkedin.com/in ASSOCIACAO CONGREGACAO DE SANTA CATARINA comprador OR compras OR suprimentos"],
    fontesConsultadas: ["https://redesantacatarina.pandape.infojobs.com.br/Detail/3657842", "https://br.linkedin.com/in/jaqueline-maria-correia-8b4798162", "https://br.linkedin.com/in/edson-matte-b6847121"],
    resultado: "Nenhum contato foi aceito: a vaga confirma a Ã¡rea corporativa, mas os perfis pÃºblicos localizados nÃ£o expÃµem conjuntamente cargo-alvo atual e vÃ­nculo atual inequÃ­voco Ã  organizaÃ§Ã£o.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2081741",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSOCIACAO DE ASSISTENCIA MUTUA A SAUDE SBC (compras OR suprimentos OR strategic sourcing OR facilities OR operaÃ§Ãµes OR administraÃ§Ã£o OR contratos OR expansÃ£o OR RH OR benefÃ­cios OR mobilidade OR supply chain)", "site:linkedin.com/in ASSOCIACAO DE ASSISTENCIA MUTUA A SAUDE SBC compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://br.linkedin.com/in/luzia-sayuri-egashira-3a13a812a"],
    resultado: "Nenhum contato foi aceito: o perfil pÃºblico confirma vÃ­nculo, mas nÃ£o expÃµe cargo-alvo corporativo atual de forma verificÃ¡vel.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-7419988", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSOCIACAO DO SANATORIO SIRIO HOSPITAL DO CORACAO cargos-alvo", "site:linkedin.com/in ASSOCIACAO DO SANATORIO SIRIO HOSPITAL DO CORACAO compras OR suprimentos OR administraÃ§Ã£o"],
    fontesConsultadas: ["https://br.linkedin.com/in/andreia-costa-22a06196", "https://br.linkedin.com/in/luciana-durante-92416226"], resultado: "Nenhum contato foi aceito: os perfis pÃºblicos confirmam vÃ­nculo, mas nÃ£o expÃµem cargo-alvo corporativo atual verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-7252455", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSOCIACAO EDUCACIONAL NOVE DE JULHO cargos-alvo", "site:linkedin.com/in ASSOCIACAO EDUCACIONAL NOVE DE JULHO compras OR suprimentos OR administraÃ§Ã£o"],
    fontesConsultadas: ["https://br.linkedin.com/in/valter-dos-santos-89957370", "https://br.linkedin.com/in/rog%C3%A9rio-gomes-da-sil-gomes-a8772130"], resultado: "Nenhum contato foi aceito: os perfis pÃºblicos tÃªm referÃªncias a compras, porÃ©m nÃ£o expÃµem cargo-alvo atual e vÃ­nculo atual inequÃ­vocos conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-5607442", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSOCIACAO HOSPITAL PERSONAL CUIDADOS ESPECIAIS cargos-alvo", "site:linkedin.com/in ASSOCIACAO HOSPITAL PERSONAL CUIDADOS ESPECIAIS compras OR suprimentos OR administraÃ§Ã£o"],
    fontesConsultadas: ["https://br.linkedin.com/in/larissa-santos-77238b15a", "https://br.linkedin.com/in/marceloomariano"], resultado: "Nenhum contato foi aceito: os perfis pÃºblicos localizados sÃ£o assistenciais e nÃ£o comprovam cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4931718", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ASSOCIACAO HOSPITALAR DO BRASIL cargos-alvo", "site:linkedin.com/in ASSOCIACAO HOSPITALAR DO BRASIL compras OR suprimentos OR administraÃ§Ã£o"],
    fontesConsultadas: ["https://br.linkedin.com/in/danielle-pompeu-silva-813a7a135", "https://br.linkedin.com/in/tatiana230117"], resultado: "Nenhum contato foi aceito: os perfis pÃºblicos localizados nÃ£o expÃµem cargo-alvo corporativo atual de forma verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  { grupoEconomicoId: "org-isol-inst-cnes-1130838", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO HOSPITALAR DO BRASIL 06087219000156 cargos-alvo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-98c87ebd", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO HOSPITALAR JAGUARA cargos-alvo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-4884124", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO HOSPITALAR NOVO HORIZONTE cargos-alvo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-4915615", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO HOSPITALAR PLATINUM cargos-alvo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3027805", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO HOSPITALAR SANTANA cargos-alvo", "site:linkedin.com/in ASSOCIACAO HOSPITALAR SANTANA compras OR suprimentos OR administraÃ§Ã£o"], fontesConsultadas: ["https://br.linkedin.com/in/luciana-aquino-9b7a7183", "https://br.linkedin.com/in/mikaelly-cristiana-4a2ba6210", "https://br.linkedin.com/in/anderson-silvino-3a455b267"], resultado: "Nenhum contato foi aceito: os perfis pÃºblicos confirmam vÃ­nculo, mas nÃ£o expÃµem cargo-alvo corporativo atual de forma verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-4428560", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO HOSPITALAR SAO MIGUEL cargos-alvo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3550301094947"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a organizaÃ§Ã£o e responsÃ¡veis estatutÃ¡rios, sem pessoa em cargo-alvo corporativo atual verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-1094947", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO HOSPITALAR SAO MIGUEL 11126276000137 cargos-alvo"], fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/associacao-hospitalar-sao-miguel-11126276000137"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a organizaÃ§Ã£o e responsÃ¡veis estatutÃ¡rios, sem pessoa em cargo-alvo corporativo atual verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-8081603", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO HOSPITALAR ZENNIT cargos-alvo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Ind_Unidade_Listar_Novo.asp?VListar=&VTipo=006"], resultado: "Nenhum contato foi aceito: a consulta pÃºblica identificou o estabelecimento, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-4249852", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO MEDICA DO HOSPITAL SAMARITANO cargos-alvo", "site:linkedin.com/in ASSOCIACAO MEDICA DO HOSPITAL SAMARITANO compras OR suprimentos OR administraÃ§Ã£o"], fontesConsultadas: ["https://www.linkedin.com/company/amhs-associa%C3%A7%C3%A3o-m%C3%A9dica-do-hospital-samaritano", "https://br.linkedin.com/in/rosangela-aparecida-garcia-a2a787128"], resultado: "Nenhum contato foi aceito: a fonte corporativa e os perfis pÃºblicos nÃ£o expÃµem cargo-alvo corporativo atual conjuntamente com vÃ­nculo inequÃ­voco.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-5434351", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASSOCIACAO PARA VALORIZACAO E PROMOCAO DE EXCEPCIONAIS cargos-alvo"], fontesConsultadas: ["https://links.prodam.sp.gov.br/noticia/compromisso-com-a-inclusao-social/"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica confirma a organizaÃ§Ã£o, sem pessoa em cargo-alvo corporativo atual verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3645045", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["ASTRA ASSESSORIA TRANSFUSIONAL SC LTDA cargos-alvo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-6932460", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BANCO DE SANGUE DE SAO PAULO E SERVCOS DE HEMOTERAPIA LTDA cargos-alvo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Conjunto.asp?VCo_Unidade=3550306932460"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-da35f807", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BANCO DE SANGUE DE SAO PAULO E SERVICOS DE HEMOTERAPIA LTDA cargos-alvo"], fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/banco-de-sangue-de-sao-paulo-e-servicos-de-hemoterapia-ltda-61369047000111"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a pessoa jurÃ­dica e administradores estatutÃ¡rios, sem pessoa em cargo-alvo corporativo atual verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-7266286", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BANCO DE SANGUE DE SAO PAULO E SEVICOS DE HEMOTERAPIA LTDA cargos-alvo"], fontesConsultadas: ["https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=3f5201e2-2801-4161-8cda-ee7da0238c0b"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-2034395", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BANCO DE SANGUE E SERVICOS DE HEMOTERAPIA LTDA cargos-alvo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3059375", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BANCO DE SANGUE SE SAO PAULO E SERVICOS DE HEMOTERAPIA LTDA cargos-alvo"], fontesConsultadas: ["https://centraldebalancos.estaleiro.serpro.gov.br/centralbalancos/servicesapi/api/Demonstracao/pdf/162986"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a pessoa jurÃ­dica, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-4798325", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BARRETO SERVICOS MEDICOS E HOSPITALARES LTDA cargos-alvo"], fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/barreto-servicos-medicos-e-hospitalares-ltda-40059417000144"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a pessoa jurÃ­dica e sÃ³cia-administradora, sem pessoa em cargo-alvo corporativo atual verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-4039904", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BE DAY CENTRO DE ESPECIALIDADES CLINICAS LTDA cargos-alvo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Ind_Unidade_Listar.asp?VComp=&VEstado=35&VListar=1&VMun=355030&VSubUni=&VTipo=62"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-1e823eac", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BENEFICENCIA NIPO BRASILEIRA DE SAO PAULO cargos-alvo"], fontesConsultadas: ["https://enkyo.org.br/wp-content/uploads/2023/09/Plano-de-Trabalho-Convenio-01-2023_compressed.pdf"], resultado: "Nenhum contato foi aceito: a fonte confirma a Ã¡rea centralizada de compras, sem perfil individual pÃºblico com cargo-alvo atual verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-9287671", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BLA SERVICOS HOSPITALARES LTDA cargos-alvo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Conjunto.asp?VCo_Unidade=3550309287671", "https://rederelief.com.br/termos-de-uso/"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-8412685", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BLANCHE DERMATOLOGIA CLINICA HOSPITALAR LTDA cargos-alvo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Ind_Unidade_Listar.asp?VComp=&VEstado=35&VListar=1&VMun=355030&VSubUni=&VTipo=36"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-5936543", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["BW MEDICA SERVICOS HOSPITALARES LTDA cargos-alvo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-4077040", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CARESURGE LTDA cargos-alvo"], fontesConsultadas: ["https://portal.prodam.sp.gov.br/documents/d/guest/cota-15-12-2024_unimed-seguros-saude-pdf"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a pessoa jurÃ­dica, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-4312813", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CARVALHO SANDRIN SERVICOS HOSPITALARES LTDA cargos-alvo"], fontesConsultadas: ["https://cebes.com.br/carvalho-sandrin-servicos-hospitalares-4312813/", "https://br.indeed.com/cmp/Carvalho-Sandrin-Servi%C3%A7os-Hospitalares"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam o estabelecimento e vaga, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-2030993", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CENTRO DE HEMATOLOGIA ONCOL SAMARITANO cargos-alvo", "site:linkedin.com/in CENTRO DE HEMATOLOGIA ONCOL SAMARITANO compras OR suprimentos OR administraÃ§Ã£o"], fontesConsultadas: ["https://www.linkedin.com/company/saude-americas"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica corporativa nÃ£o expÃµe pessoa em cargo-alvo vinculada de modo inequÃ­voco Ã  organizaÃ§Ã£o pesquisada.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-2089483", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CENTRO MEDICO ESPECIALIZADO S C LTDA cargos-alvo", "site:linkedin.com/in CENTRO MEDICO ESPECIALIZADO S C LTDA compras OR suprimentos OR administraÃ§Ã£o"], fontesConsultadas: ["https://br.linkedin.com/in/renata-moraes-07502759"], resultado: "Nenhum contato foi aceito: o perfil pÃºblico refere experiÃªncia passada de terceiro, sem vÃ­nculo atual e cargo-alvo corporativo verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3160548", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CERPO CENTRO DE RECUPERACAO DE PATOLOGIAS OCULARES LTDA cargos-alvo", "site:linkedin.com/in CERPO compras OR suprimentos OR administraÃ§Ã£o"], fontesConsultadas: ["https://br.linkedin.com/in/brenda-borlone-silveira-548006221", "https://br.linkedin.com/in/cristiano-souza-66b10625"], resultado: "Nenhum contato foi aceito: os perfis pÃºblicos encontrados nÃ£o expÃµem cargo-alvo corporativo atual e vÃ­nculo atual inequÃ­vocos conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3183203", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CESMO HOSPITAL ESPECIALIZADO EM OFTALMOLOGICA LTDA cargos-alvo", "site:linkedin.com/in CESMO compras OR suprimentos OR administraÃ§Ã£o"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: as consultas pÃºblicas nÃ£o retornaram perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3518205", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CETENE CENTRO DE TERAPIA NEFROLOGICA LTDA cargos-alvo"], fontesConsultadas: ["https://prefeitura.sp.gov.br/web/saude/w/acesso_a_informacao/360437"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica confirma a organizaÃ§Ã£o e contrato, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3353710", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CHREICHI CLINICA MEDICA LTDA cargos-alvo"], fontesConsultadas: ["https://drachreichi.com.br/politica-de-privacidade/"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a organizaÃ§Ã£o e canal corporativo, sem pessoa em cargo-alvo corporativo verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-985bc2a5", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CIENTIFICALAB PRODUTOS LABORATORIAIS E SISTEMAS LTDA cargos-alvo"], fontesConsultadas: ["https://cientificalab.com.br/historia"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica corporativa descreve a organizaÃ§Ã£o, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3294536", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CLINICA ALPHA SP SAUDE EIRELI cargos-alvo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Conjunto.asp?VCo_Unidade=3550303294536"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento e telefone central, sem pessoa em cargo-alvo corporativo verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3786064", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CLINICA DE GINECOLOGIA OBSTETRICIA E MASTOLOGIA LUIZ ANCHIETA cargos-alvo"], fontesConsultadas: ["https://www.alumnidayhospital.com.br/institucional/day-hospital/"], resultado: "Nenhum contato foi aceito: a fonte institucional identifica a clÃ­nica, sem perfil individual com vÃ­nculo e cargo-alvo corporativo verificÃ¡veis.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3765415", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CLINICA DE OLHOS DR SUEL ABUJAMRA cargos-alvo"], fontesConsultadas: ["https://www.metrus.org.br/downloads/prestadores_site.pdf"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a organizaÃ§Ã£o e telefone central, sem pessoa em cargo-alvo corporativo verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-3793478", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CLINICA DE RETAGUARDA HOSPITALAR MOEMA LTDA cargos-alvo"], fontesConsultadas: ["https://consultacnes.com/estabelecimento/3793478-clinica-de-retaguarda-hospitalar-moema-sao-paulo-sp"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento, sem pessoa em cargo-alvo corporativo verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  { grupoEconomicoId: "org-isol-inst-cnes-609005", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["CLINICA DR MARCELO NISENBAUM GINECOLOGIA E OBSTETRICIA LTDA cargos-alvo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Conjunto.asp?VCo_Unidade=3550300609005"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica o estabelecimento e telefone central, sem pessoa em cargo-alvo corporativo verificÃ¡vel.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA" },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4746619",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA DRA ALESSANDRA FERNANDEZ SERVICOS MEDICOS HOSPITALARES compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=82137d7f-ce2b-4fa0-853c-06fe17ebd6fa"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica confirma a pessoa jurÃ­dica e sua atividade, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-87114",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA DRA NATALIA CANDIDO DE CASTRO GINECOLOGIA E OBSTETRICIA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/clinica-dra-natalia-candido-de-castro-ginecologia-e-obstetricia-ltda-22534238000130"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica cadastral identifica a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-5613701",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA GOTFRYD SERVICOS HOSPITALARES LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://diariooficial.santos.sp.gov.br/edicoes/inicio/download/2024-04-22", "https://www.econodata.com.br/consulta-empresa/09132830000147-clinica-gotfryd-servicos-hospitalares-ltda"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam a organizaÃ§Ã£o e sua atividade, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-5674727",
    dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA MEDICA JD ROBRU SC LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://hospitaleclinicas.com.br/cnes/5674727/clinica-medica-jd-robru", "https://cnes2.datasus.gov.br/Mod_Ind_Unidade_Listar.asp?VComp=201702&VEstado=35&VListar=1&VMun=&VSubUni=&VTipo=36"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam o estabelecimento, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.",
    confianca: "ALTA",
    status: "SEM_CONTATO_VERIFICAVEL",
    statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-9652027", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA MEDICA MANTELLI LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/clinica-medica-mantelli-ltda-23480926000127"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica cadastral identifica a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-457442", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA MEDICA MARCOS ROBERTO DE OLIVEIRA TACCONI LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://monitorcnpj.com.br/cnpj/36431196000116/", "https://cebes.com.br/tacconi-servicos-medicos-e-hospitalares-457442/"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e o estabelecimento, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3537331", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA MEDICA NOSSA SENHORA LURDES LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: [],
    resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-9f38ff0f", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA MIYAKE LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://hospitaleclinicas.com.br/cnes/3347966/clinica-miyake", "https://diariooficial.prefeitura.sp.gov.br/md_epubli_visualizar.php?21SyzIav5KbA3mNfKJRlPwWHM3UsT01uhZKYPMhMQqVrTwlnIchLSkyu9LyOYtjX0j31mGSve8NgXskDQu02MEP3mUSzvfMwcOi7eKf19iXqNYGFPNU7xAuA8W5R9h4X="],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3275337", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA OFTALMOLESTE LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://www.escavador.com/diarios/849139/DOESP/cidade-de-sao-paulo/2010-11-17?page=20"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica menciona a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-fbe8b89d", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA OFTALMOLOGICA SANTA VIRGINIA LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Ambulatorial.asp?VCo_Unidade=3550307582285", "https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=90187cbc-b506-4eeb-b274-8af11f396131"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2979101", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CLINICA VENTURA MEDICA LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://www.situacaocadastral.info/cnpj/clinica-ventura-medica-ltda-46846779000161"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica cadastral identifica a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3019934", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["COMPLEXO HOSPITALAR PAULISTA LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://web.trf3.jus.br/acordaos/Acordao/BuscarDocumentoGedpro/7417353", "https://www.gov.br/mme/pt-br/arquivos/do-17-09-2012-s1.pdf"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e seu contexto institucional, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3427285", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CPU CLINICA DE PROCEDIMENTOS UROLOGICOS LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://www.gov.br/mme/pt-br/arquivos/do-25-02-2011-s3.pdf"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica confirma contrataÃ§Ã£o da organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2078589", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CRUZ AZUL DE SAO PAULO compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://www.cruzazulsp.net.br/Institucional/Transparencia-232?m=47", "https://pubhtml5.com/kiil/mjjv/basic/"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam a estrutura de compras da organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2080494", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["CRUZ VERMELHA BRASILEIRA FILIAL DO ESTADO DE SAO PAULO compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://observasampaparcerias.prefeitura.sp.gov.br/web/controladoria_geral/w/transparencia_covid19/298152", "https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=15622600-4a3a-49fb-9b78-9b01e744efb3"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e seu contexto de gestÃ£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-108782", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["DE LEO SERVICOS HOSPITALARES LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://consultacnes.com/estabelecimento/108782-de-leo-servicos-hospitalares-ltda-sao-paulo-sp", "https://brazilguide.net/c/de-leo-servicos-hospitalares-ltda-35546194000100"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e o estabelecimento, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4787072", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["DERMATOLOGIA HOSPITALAR SS LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://cnpj.biz/24658597000124"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica cadastral identifica a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-dad8fb19", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["DIAGNOSTICO DA AMERICA SA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://br.linkedin.com/in/ver%C3%B4nica-machado-72b9b224a", "https://www.saobernardo.sp.gov.br/documents/10181/1441964/NM%2B2296%2Bde%2B27.05.2022%2B-%2BConteu%CC%81do%2BIntegral.pdf/2c73ad04-2731-f28a-6128-0ca077c4aa2c"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam vÃ­nculo organizacional, mas nÃ£o expÃµem cargo-alvo corporativo atual verificÃ¡vel conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-8ff94d38", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["DIAGNOSTICOS DA AMERICA S A compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://br.linkedin.com/in/edina-rosa-3139a021", "https://br.linkedin.com/in/m%C3%A1rcio-ferreira-a2a149a2"],
    resultado: "Nenhum contato foi aceito: os perfis pÃºblicos confirmam vÃ­nculo organizacional, mas nÃ£o expÃµem cargo-alvo corporativo atual verificÃ¡vel conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3645053", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["DIOSP SERVICOS MEDICOS SC LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: [],
    resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-1159224", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["EIGHT MATERIAIS E INSUMOS HOSPITALARES compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Conjunto.asp?VCo_Unidade=3550301159224", "https://cnpj.biz/03082036000150"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e o estabelecimento, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-6189848c", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["ESHO EMPRESA DE SERVICOS HOSPITALARES SA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://www.econodata.com.br/consulta-empresa/29435005011325-esho-empresa-de-servicos-hospitalares-sa", "https://cliniguia.com/unidades/sao-paulo-sp/hospital-vitoria-6668143/"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e a unidade, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-8454310", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["FLUGEL SERVICOS MEDICOS HOSPITALARES LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://www.consultascnpj.com/flugel-servicos-medicos-hospitalares-ltda/58434554000187"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica cadastral identifica a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-9263063", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["FPM SERVICOS ODONTOLOGICOS E HOSPITALARES EIRELI compras OR suprimentos OR administrativo"],
    fontesConsultadas: [],
    resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2078015", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["FUNDACAO FACULDADE DE MEDICINA MEC MPAS compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://bvsms.saude.rj.gov.br/bvs/saudelegis/saes/2022/prt0220_15_07_2022.html", "https://fns2.saude.gov.br/propostaconvenio/conv_imprimir.asp?co_seq_proposta=93763"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a instituiÃ§Ã£o e sua unidade, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-208304a8", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["FUNDACAO JOSE LUIZ SETUBAL compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/fundacao-jose-luiz-egydio-setubal-61213674000320", "https://fundacaojles.org.br/quem-somos/governanca-respira-backup-20260708102418/"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam estrutura de governanÃ§a, mas nÃ£o expÃµem pessoa identificada com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2089785", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["FUNDACAO OSWALDO RAMOS compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://br.linkedin.com/in/renato-camargo-l030624", "https://www.informecadastral.com.br/cnpj/fundacao-oswaldo-ramos-52803319001120"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam vÃ­nculo organizacional, mas nÃ£o expÃµem cargo-alvo corporativo atual verificÃ¡vel conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-952ff8b9", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["G S H CORP PARTICIPACOES S A compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://consultacnes.com/estabelecimento/2935201-g-s-h-corp-participacoes-s-a-brasilia-df", "https://www.gov.br/hfa/pt-br/acesso-a-informacao/receitas-e-despesas/ARQUIVOS_CRONOLOGIA_PGTO_POR_ANO/arquivos-2024/2022/09.CRONOLOGIAPGTOSETEMBRO2022ENVIADA.pdf/%40%40display-file/file"],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e registros de contrataÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-9614117", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["GEAH GRUPO ESPECIALIZADO EM ANESTESIOLOGIA HOSPITALAR LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://santacasavotuporanga.com.br/scv/transparencia/repositorio/5eb115352da2a1f9e6c9626f1ab568a4.pdf"],
    resultado: "Nenhum contato foi aceito: a fonte pÃºblica confirma contrataÃ§Ã£o da organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-9000445", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["GEN SERVICOS MEDICOS E HOSPITALARES LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: [],
    resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-7676484", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["GERHOSP SERVICOS HOSPITALARES LTDA compras OR suprimentos OR administrativo"],
    fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3550307676484", "https://diariooficial.prefeitura.sp.gov.br/md_epubli_visualizar.php?XUEjmbXvkQ3wwKxRon0njfJTs4xecD1U5EDZiyzOJ_i9SqWFMqT7Ijf9xY5zW1BDRXS0h96OR9Nh_gOAjqpH5bNY2_Kzet_bdF1E_-_BUd9P8zq2x900KqWw6O8r9OdB="],
    resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e a unidade, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-7622600", dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: ["GLOBAL MED SERVICOS MEDICOS E HOSPITALARES EIRELI EPP compras OR suprimentos OR administrativo"],
    fontesConsultadas: [],
    resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-5996376", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["GONCALVES ASSIST MEDICA E HOSPITALAR LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-7159102", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["GREEN HILL SERVICOS MEDICOS SC LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3550307159102"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica identifica a organizaÃ§Ã£o e direÃ§Ã£o clÃ­nica, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2089696", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["GRUPO DE APOIO AO ADOLESCENTE E A CRIANCA COM CANCER GRAACC compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://graacc.org.br/wp-content/uploads/2023/03/4.1-Plano-Trabalho-No-01510_2022-SPSP.pdf", "https://graacc.org.br/doador-mensal/"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam a existÃªncia de Ã¡rea de suprimentos e canais institucionais, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo atual verificÃ¡vel conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2078635", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["GRUPO ITASA LIFE LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://www.econodata.com.br/consulta-empresa/52843158000127-grupo-itasa-life-ltda", "https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=1238ac6b-9e0a-4ac4-a1a7-c02140de0b2c"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2084368", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HAPVIDA NOTRE DAME INTERMEDICA SAUDE S A compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://www4.tjrj.jus.br/camarasweb/listaPauta.aspx?pDataSessao=23%2F09%2F2025+10%3A01%3A00&pOJ=12266"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-41a4c41a", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HCLOE HOSPITAL DE OLHOS LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://www.hcloe.com.br/", "https://www.informecadastral.com.br/cnpj/hcloe-hospital-de-olhos-ltda-61367520000121"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-9182985", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOME CARE CENE HOSPITALLAR LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://portal-adm.campinas.sp.gov.br/node/36640", "https://www.imprensaoficial.com.br/doflash/prototipo/2020/Setembro/12/exec1/pdf/pg_0138.pdf"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas confirmam contratos da organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-4060105", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAIS INTEGRADOS DA GAVEA S A compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://transparencia.mpf.mp.br/conteudo/diarios-e-boletins/diario-oficial-da-uniao-1/2026/dou3_2026_03_10.pdf", "https://br.linkedin.com/in/luis-carlos-silveira-dos-santos-165a651a3"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e vÃ­nculo profissional, mas nÃ£o expÃµem cargo-alvo corporativo atual verificÃ¡vel conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-949035", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL ALEMAO OSWLADO CRUZ compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://ishaoc.org.br/contratacoes/", "https://www.hospitaloswaldocruz.org.br/imprensa/hospital-na-midia/ia-otimiza-estoque-do-hospital-oswaldo-cruz-e-automatiza-separacao-de-medicamentos/"], resultado: "Nenhum contato foi aceito para esta unidade duplicada: os perfis pÃºblicos localizados foram associados Ã  organizaÃ§Ã£o correlata jÃ¡ coberta, sem vÃ­nculo inequÃ­voco com esta unidade especÃ­fica.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-91fd082b", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL ALVORADA TAGUATINGA LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://portaldatransparencia.gov.br/busca/pessoa-juridica/08100676000169", "https://www.senado.leg.br/transparencia/liccontr/contratos/empresas_E.asp"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e contratos, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
{
    grupoEconomicoId: "org-isol-inst-cnes-4060105", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAIS INTEGRADOS DA GAVEA S A compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://transparencia.mpf.mp.br/conteudo/diarios-e-boletins/diario-oficial-da-uniao-1/2026/dou3_2026_03_10.pdf", "https://br.linkedin.com/in/luis-carlos-silveira-dos-santos-165a651a3"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e vÃ­nculo profissional, mas nÃ£o expÃµem cargo-alvo corporativo atual verificÃ¡vel conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2879441", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL BDW SP LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://prefeitura.sp.gov.br/web/licenciamento/w/desenvolvimento_urbano/participacao_social/conselhos_e_orgaos_colegiados/cppu/327392", "https://www.emis.com/php/company-profile/BR/Hospital_Bdw_Sp_Ltda_pt_15455975.html"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e sua administraÃ§Ã£o societÃ¡ria, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo atual verificÃ¡vel conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-5883741", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL BENVISTA LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/hospital-benvista-ltda-59545778000129"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica cadastral identifica a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3986683", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL DA FACE LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://hospitaldaface.com.br/contato/", "https://www.econodata.com.br/consulta-empresa/07192194000113-hospital-da-face-ltda"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o e responsÃ¡vel tÃ©cnico assistencial, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-6032745", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL ALVORADA TAQUATINGA LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://www.senado.leg.br/transparencia/liccontr/contratos/empresas_E.asp"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo e vÃ­nculo atual inequÃ­voco para esta unidade.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-2879441", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL BDW SP LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://prefeitura.sp.gov.br/web/licenciamento/w/desenvolvimento_urbano/participacao_social/conselhos_e_orgaos_colegiados/cppu/327392", "https://www.emis.com/php/company-profile/BR/Hospital_Bdw_Sp_Ltda_pt_15455975.html"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, mas nÃ£o expÃµem pessoa com cargo-alvo corporativo atual verificÃ¡vel conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-5883741", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL BENVISTA LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/hospital-benvista-ltda-59545778000129"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica cadastral identifica a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3986683", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL DA FACE LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://hospitaldaface.com.br/contato/", "https://www.econodata.com.br/consulta-empresa/07192194000113-hospital-da-face-ltda"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam responsÃ¡vel tÃ©cnico assistencial, mas nÃ£o pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3019012", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL DE CLINICAS JARDIM HELENA SC LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://hospitaleclinicas.com.br/cnes/3019012/hosp-de-clinicas-j-helena", "https://esaj.tjsp.jus.br/cjsg/getArquivo.do?cdAcordao=15252180&cdForo=0"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam a organizaÃ§Ã£o, sem pessoa em cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3701832", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL DE ESPECIALIDADES SILVIO ROMERO LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://cnes2.datasus.gov.br/Mod_Ambulatorial.asp?VCo_Unidade=3550303701832", "https://www.escavador.com/diarios/495813/DOESP/executivo-i/2017-07-11?page=44", "https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=e67f5252-5001-40ee-90e9-e4b44368156b"], resultado: "Nenhum contato foi aceito: as fontes pÃºblicas identificam Ã¡rea administrativa histÃ³rica, sem comprovaÃ§Ã£o de vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-8064695", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL DE FERIDAS LTDA compras OR suprimentos OR administrativo"], fontesConsultadas: ["https://casadosdados.com.br/solucao/cnpj/hospital-de-feridas-ltda-53624313000187"], resultado: "Nenhum contato foi aceito: a fonte pÃºblica cadastral identifica a organizaÃ§Ã£o, mas nÃ£o expÃµe pessoa com cargo-alvo corporativo e vÃ­nculo atual verificÃ¡veis conjuntamente.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  {
    grupoEconomicoId: "org-isol-inst-cnes-3751112", dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: ["HOSPITAL DIA DR IVAN VARGAS EIRELI compras OR suprimentos OR administrativo"], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a consulta pÃºblica nÃ£o retornou fonte verificÃ¡vel que reÃºna pessoa, cargo-alvo corporativo e vÃ­nculo atual Ã  organizaÃ§Ã£o.", confianca: "ALTA", status: "SEM_CONTATO_VERIFICAVEL", statusRevisao: "APROVADA",
  },
  ...([
    ["org-isol-inst-cnes-4077164", "HOSPITAL DIA MONTE CRISTO LTDA", []],
    ["org-isol-inst-cnes-5698723", "HOSPITAL DOS OLHOS ABC LTDA", ["https://cnpja.com/office/60603535000189"]],
    ["org-isol-inst-cnes-3559203", "HOSPITAL E MATERNIDADE JARDINS LTDA", ["https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3550303559203", "https://acordaos.economia.gov.br/solr/acordaos2_shard11_replica_n60/browse?annotateBrowse=true"]],
    ["org-isol-inst-cnes-2077604", "HOSPITAL E MATERNIDADE PRESIDENTE SOCIEDADE SIMPLES", ["https://www.gov.br/pgfn/pt-br/assuntos/divida-ativa-da-uniao/transparencia-fiscal-1/painel-dos-parcelamentos/termos-de-transacao/3a-regiao/termo-de-transacao-individual-hospital-e-maternidade-presidente-sociedade-simples.pdf/view"]],
    ["org-isol-inst-cnes-2080257", "HOSPITAL E MATERNIDADE SANTA MARINA LTDA", []],
    ["org-isol-inst-cnes-2078619", "HOSPITAL E MATERNIDADE SAO MIGUEL S A", []],
    ["org-isol-inst-cnes-3314596", "HOSPITAL E MATERNIDADE TALITA LTDA", []],
    ["org-7d60be1d", "HOSPITAL E MATERNIDADE VIDAS LTDA", []],
    ["org-isol-inst-cnes-2091801", "HOSPITAL E PRONTO SOCORRO COMUNITARIO VILA IOLANDA LTDA", []],
    ["org-isol-inst-cnes-2823209", "HOSPITAL E PRONTO SOCORRO PORTINARI LTDA", []],
    ["org-isol-inst-cnes-507733", "HOSPITAL ESPORTE E SAUDE LTDA", []],
    ["org-isol-inst-cnes-5648483", "HOSPITAL GRANJA JULIETA LTDA", []],
    ["org-isol-inst-cnes-5429439", "HOSPITAL IBIRAPUERA LTDA", []],
    ["org-isol-inst-cnes-5710979", "HOSPITAL INGLES LTDA", []],
    ["org-isol-inst-cnes-3528189", "HOSPITAL ITATIAIA LTDA", []],
    ["org-36fa1475", "HOSPITAL LEFORTE LIBERDADE S A", []],
    ["org-44c671ff", "HOSPITAL LEFORTE S A", []],
    ["org-isol-inst-cnes-819158", "HOSPITAL ODONTOLOGICO PAULISTA LTDA", []],
    ["org-isol-inst-cnes-9490604", "HOSPITAL SAGRADA FAMILIA LTDA", []],
    ["org-isol-inst-cnes-5040787", "HOSPITAL SAN GENNARO LTDA", []],
  ] as [string, string, string[]][]).map(([grupoEconomicoId, nome, fontes]) => ({
    grupoEconomicoId, dataPesquisa: "2026-09-05T00:00:00.000Z",
    termosConsulta: [`${nome} compras OR suprimentos OR administrativo`], fontesConsultadas: fontes,
    resultado: "Nenhum contato foi aceito: as consultas pÃºblicas nÃ£o retornaram perfil individual verificÃ¡vel que reÃºna vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA" as NivelConfianca, status: "SEM_CONTATO_VERIFICAVEL" as StatusPesquisaContato, statusRevisao: "APROVADA" as StatusRevisao,
  })),
  ...([
    ["org-isol-inst-cnes-2079445", "HOSPITAL SANTA ISABEL", ["https://rededor.gupy.io/jobs/11969653?jobBoardSource=gupy_public_page", "https://www.vagas.com.br/vagas/v2705282/auxiliar-de-suprimentos-setor-almoxarifado-unidade-hospital-santa-isabel"]],
    ["org-isol-inst-cnes-9048464", "HOSPITAL SANTA MONICA LTDA", ["https://hospitalsantamonica.com.br/politica-de-privacidade/", "https://www.solutudo.com.br/empresas/sp/s-paulo/hospitais/hospital-santa-monica-ltda-12324657"]],
    ["org-isol-inst-cnes-2089580", "HOSPITAL SANTA PAULA S A", ["https://casadosdados.com.br/solucao/cnpj/hospital-santa-paula-sa-60777901000205", "https://drive.prefeitura.sp.gov.br/cidade/secretarias/upload/pg_0042_pg_0043_merged.pdf"]],
    ["org-isol-inst-cnes-5648491", "HOSPITAL SAO JUDAS LTDA", ["https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=3ed9c019-bc54-4766-a39d-29ec4225d8a1", "https://sig.ufsj.edu.br/public/jsp/contratos/contrato_detalhamento.jsf?idContrato=1220"]],
  ] as [string, string, string[]][]).map(([grupoEconomicoId, nome, fontes]) => ({ grupoEconomicoId, dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: [`${nome} compras OR suprimentos OR administrativo`], fontesConsultadas: fontes, resultado: "Nenhum contato foi aceito: as fontes pÃºblicas consultadas nÃ£o expÃµem perfil individual verificÃ¡vel com vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA" as NivelConfianca, status: "SEM_CONTATO_VERIFICAVEL" as StatusPesquisaContato, statusRevisao: "APROVADA" as StatusRevisao })),
  ...([
    ["org-isol-inst-cnes-5969271", "HOSPITAL UNITY LTDA", ["https://www.jusbrasil.com.br/jurisprudencia/tj-sp/5222923843/inteiro-teor-5222923852", "https://www.solutudo.com.br/empresas/sp/s-paulo/hospitais/hospital-unity-ltda-22441058"]],
    ["org-isol-inst-cnes-3185621", "HOSPITALITA ATENDIMENTO DOMICILIAR EM SAUDE LTDA", ["https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=cc05ade8-f4c9-4ebc-96ed-2df159b73fb3", "https://www.cnpj.pro/info/05615338000171"]],
    ["org-isol-inst-cnes-5357527", "HUZZO HOSPITAL DOMICILIAR LTDA", ["https://casadosdados.com.br/solucao/cnpj/huzzo-hospital-domiciliar-ltda-36978084000180", "https://cnpj.biz/60403492000198"]],
    ["org-isol-inst-cnes-400106", "IAROSSI E AFFONSO ODONTOLOGICO LTDA", []],
    ["org-ea0b106e", "IMPAR SERVICOS HOSPITALARES S A", ["https://portaldatransparencia.gov.br/pessoa-juridica/60884855002440", "https://cnpjaberto.com.br/cnpj/60884855000154"]],
    ["org-isol-inst-cnes-7240481", "IN CARE HOSPITAL DE REABILITACAO E LONGA PERMANENCIA LTDA", []],
    ["org-isol-inst-cnes-1062379", "INCARE HOSPITAL DE TRANSICAO LTDA 33865712000556", ["https://cnes2.datasus.gov.br/Mod_Ambulatorial.asp?VCo_Unidade=3550300105392"]],
    ["org-isol-inst-cnes-1036750", "INCARE HOSPITAL DE TRANSICAO LTDA CNPJ 33865712000122", ["https://cnes2.datasus.gov.br/Mod_Ambulatorial.asp?VCo_Unidade=3550300105392"]],
    ["org-isol-inst-cnes-5571006", "INFYCONTROL PREVENCAO DE INFECCOES HOSPITALARES LTDA", []],
    ["org-isol-inst-cnes-3166597", "INSTITUICAO PAULISTA ADVENTISTA DE EDUC E ASS SOCIAL", []],
    ["org-7cf2fec4", "IRMANDADE DA SANTA CASA DE MISERICORDIA DE SAO PAULO", []],
    ["org-37c0fd79", "JAVIER CARBAJAL ALLERGY AND IMMUNOLOGY INSTITUTE LTDA", []],
    ["org-isol-inst-cnes-9810692", "JB CENTRO DIAGNOSTICO DE PATOLOGIA ANALIA FRANCO LTDA", []],
    ["org-isol-inst-cnes-1137646", "JCM HOSPITALAR LTDA CNPJ 46926645000150", ["https://www.econodata.com.br/consulta-empresa/46926645000150-jcm-hospitalar-ltda"]],
    ["org-isol-inst-cnes-9018875", "JFCL CLINICA DE MEDICINA HOSPITALAR LTDA EPP", []],
    ["org-isol-inst-cnes-3061957", "JH MEDICINA HOSPITALAR LTDA", ["https://cnpjcheck.com.br/empresa/jh-medicina-hospitalar-ltda-46927675000181"]],
    ["org-isol-inst-cnes-5822602", "JLB SERVICOS HOSPITALARES DE OFTALMOLOGIA LTDA", ["https://www.econodata.com.br/consulta-empresa/55252967000152-jlb-servicos-hospitalares-de-oftalmologia-ltda"]],
    ["org-b95a457a", "JM HEALTHCARE HOSPITAL DE TRANSICAO LTDA", ["https://www.jusbrasil.com.br/processos/nome/652696890/jm-healthcare-hospital-de-transicao-ltda", "https://www.saudedafamilia.org/wp-content/uploads/2023/05/contrato.pdf"]],
    ["org-isol-inst-cnes-788503", "JM SERVICOS MEDICOS E HOSPITALARES LTDA", []],
    ["org-isol-inst-cnes-9652221", "JML SERVICOS HOSPITALARES LTDA", ["https://cnes2.datasus.gov.br/Mod_Conjunto.asp?VCo_Unidade=3550309652221", "https://rederelief.com.br/termos-de-uso/"]],
  ] as [string, string, string[]][]).map(([grupoEconomicoId, nome, fontes]) => ({ grupoEconomicoId, dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: [`${nome} compras OR suprimentos OR administrativo`], fontesConsultadas: fontes, resultado: "Nenhum contato foi aceito: as fontes publicas consultadas nao expoem perfil individual verificavel com vinculo atual e cargo-alvo corporativo.", confianca: "ALTA" as NivelConfianca, status: "SEM_CONTATO_VERIFICAVEL" as StatusPesquisaContato, statusRevisao: "APROVADA" as StatusRevisao })),
  ...([
    ["org-13e88174", "REAL E BENEMERITA ASSOCIACAO PORTUGUESA DE BENEFICENCIA", ["https://faculdadebp.com.br/wp-content/uploads/2025/10/Regimento-Geral-BP-Educacao-Ensino-Superior-em-Saude_29.09.25-1.pdf"]],
    ["org-17825d71", "SAO LUCAS HEMOTERAPIA E HEMATOLOGIA SS LTDA", ["https://cnes2.datasus.gov.br/Mod_Basico.asp?VCo_Unidade=3518807422652", "https://br.linkedin.com/company/hemocentro-sao-lucas"]],
    ["org-22379759", "CEMA HOSPITAL ESPECIALIZADO LIMITADA", ["https://br.linkedin.com/company/cema-hospital-especializado-ltda", "https://pt.linkedin.com/posts/cema-hospital-especializado-ltda_vagas-rh-activity-7472712139368165376-XvFV"]],
    ["org-2a58efa7", "ASSOCIACAO FUNDO DE INCENTIVO A PESQUISA", ["https://pt.linkedin.com/posts/afipbrasil_a-afip-associa%C3%A7%C3%A3o-fundo-de-incentivo-%C3%A0-pesquisa-activity-7417638438004215808-_oNG"]],
    ["org-4d42679b", "ONCO STAR SP ONCOLOGIA LTDA", []],
    ["org-627ee072", "SOCIEDADE BENEFICENTE DE SENHORAS HOSPITAL SIRIO LIBANES", ["https://pt.linkedin.com/posts/michelle-breitenborn-di-cicco-2a75b6167_oportunidade-comprador-pleno-hospital-activity-7443284509623484416-PL-O", "https://br.linkedin.com/in/matheus-martins-dos-anjos-191ab8150"]],
    ["org-681eaad6", "PREVENT SENIOR ATENDIMENTO A SAUDE LTDA", []],
    ["org-79399e8c", "SANTO ANDRE SERVICOS MEDICOS ESPECIALIZADOS LTDA", []],
    ["org-7d8f25e8", "CLINICA PREMIUM CARE SAUDE LTDA", []],
    ["org-987d065a", "U S O UNIDADE SANTANA DE OFTALMOLOGIA LTDA", []],
    ["org-aa1f20b8", "HOSPITAL ALEMAO OSWALDO CRUZ", []],
    ["org-ad2feff3", "NOTRE DAME INTERMEDICA SAUDE S A", []],
    ["org-b590004c", "UNIDADE OFTALMOLOGICA DE SANTANA LTDA", []],
    ["org-b848ef6c", "REDE MORIAH SAUDE LTDA", []],
    ["org-c85b0bb6", "SOCIEDADE BENEFICENTE SAO CAMILO", ["https://saocamilo-sp.br/_app/views/publicacoes/outraspublicacoes/Anu%C3%A1rio%20Final_.pdf", "https://diariooficial.prefeitura.sp.gov.br/md_epubli_visualizar.php"]],
    ["org-d753d961", "REDE DOR SAO LUIZ S A", ["https://pt.wikipedia.org/wiki/Rede_D%27Or_S%C3%A3o_Luiz"]],
    ["org-d83bf092", "ASSOCIACAO BENEFICENTE EBENEZER", ["https://br.linkedin.com/company/ciesglobal", "https://www.imprensaoficial.com.br/Certificacao/GatewayCertificaPDF.aspx?notarizacaoID=78f5a113-882a-42bb-a58f-8eed7e8b2a2a"]],
    ["org-e8caa657", "FLEURY S A", ["https://www.linkedin.com/company/grupo-fleury", "https://br.linkedin.com/in/rafael-zimmermann-41308a84"]],
    ["org-isol-inst-cnes-1059556", "SIM HOSPITAL DIA LTDA CNPJ 42792272000111", []],
    ["org-isol-inst-cnes-1134159", "SANTA SARA SERVICOS MEDICOS E HOSPITALARES 25265283000124", []],
  ] as [string, string, string[]][]).map(([grupoEconomicoId, nome, fontes]) => ({ grupoEconomicoId, dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: [`${nome} compras OR suprimentos OR administrativo`], fontesConsultadas: fontes, resultado: "Nenhum contato foi aceito: as fontes pÃºblicas consultadas nÃ£o expÃµem perfil individual verificÃ¡vel com vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA" as NivelConfianca, status: "SEM_CONTATO_VERIFICAVEL" as StatusPesquisaContato, statusRevisao: "APROVADA" as StatusRevisao })),
  ...([
    ["org-isol-inst-cnes-2032236", "PLENA SAUDE S A", []],
    ["org-isol-inst-cnes-2032945", "SAGA ASSISTENCIA MEDICA SC LTDA", []],
    ["org-isol-inst-cnes-2058391", "SOCIEDADE BENEFICENTE ISRAELITA BRAS HOSP ALBERT EINSTEIN", []],
    ["org-isol-inst-cnes-2075288", "UNIDADE DE HEMOTERAPIA E HEMATOLOGIA SAMARITANO", []],
    ["org-isol-inst-cnes-2077388", "SPDM PAIS HOSPITAL AMPARO MATERNAL", []],
    ["org-isol-inst-cnes-2077485", "SPDM ASSOCIACAO PAULISTA PARA O DESENVOLVIMENTO DA MEDICIN", []],
    ["org-isol-inst-cnes-2078570", "SPDM ASSOC PAULISTA PARA O DESENVOLVIMENTO DA MEDICINA", []],
    ["org-isol-inst-cnes-2080974", "HOSPITAL PAULISTA LTDA", []],
    ["org-isol-inst-cnes-2082314", "LAPA ASSISTENCIA MEDICA LTDA", []],
    ["org-isol-inst-cnes-2082624", "SOCIEDADE BRASILEIRA E JAPONESA DE BENEFICIENCIA SANTA CRUZ", []],
    ["org-isol-inst-cnes-2089602", "SERV SOCIAL DA IND DO PAPEL PAPELAO E CORT DO ESTADO DE SP", []],
    ["org-isol-inst-cnes-217220", "SERVICOS DE HEMOTERAPIA MADRE REGINA LTDA", []],
    ["org-isol-inst-cnes-266167", "HOSPITAL ALVORADA TAGUATINGA S A", []],
    ["org-isol-inst-cnes-2688581", "IRMANDADE SANTA CASA DE MISERICORDIA DE SAO PAULO", []],
    ["org-isol-inst-cnes-2688603", "ASSOCIACAO CONGREGACAO DESANTA CATARINA", []],
    ["org-isol-inst-cnes-2819473", "SERRA MAYOR SERVICOS MEDICOS S A", []],
    ["org-isol-inst-cnes-2891387", "UNITA SERVICOS MEDICOS HOSPITALARES LTDA", []],
    ["org-isol-inst-cnes-2895501", "MGGIUSA SERVICOS MEDICOS E HOSPITALARES LTDA", []],
    ["org-isol-inst-cnes-2934973", "SOPED GESTAO HOSPITALAR LTDA", []],
    ["org-isol-inst-cnes-2935015", "TERAENDO HOSPITALAR LTDA", []],
  ] as [string, string, string[]][]).map(([grupoEconomicoId, nome, fontes]) => ({ grupoEconomicoId, dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: [`${nome} compras OR suprimentos OR administrativo`], fontesConsultadas: fontes, resultado: "Nenhum contato foi aceito: as fontes pÃºblicas consultadas nÃ£o expÃµem perfil individual verificÃ¡vel com vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA" as NivelConfianca, status: "SEM_CONTATO_VERIFICAVEL" as StatusPesquisaContato, statusRevisao: "APROVADA" as StatusRevisao })),
  ...([
    ["org-isol-inst-cnes-3143740", "PRECORDIO ASSISTENCIA MEDICO HOSPITALAR S S LTDA"], ["org-isol-inst-cnes-3291219", "MULTICLIN SERVICOS MEDICOS LTDA"], ["org-isol-inst-cnes-3308227", "RENAITRE CLINICA DE ESTETICA LTDA"], ["org-isol-inst-cnes-3439658", "LCL SERVICOS MEDICOS HOSPITALARES LTDA"], ["org-isol-inst-cnes-3476634", "NEOCOR S C LTDA"], ["org-isol-inst-cnes-3477355", "PREMIER RESIDENCE HOSPITAL S A"], ["org-isol-inst-cnes-3483096", "SAHA SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-3738272", "VICTRICE SERVICOS MEDICOS E HOSPITALARES SS"], ["org-isol-inst-cnes-3751260", "LEONARDO FACCHINETTI SERVICOS HOSPITALARES LTDA"], ["org-isol-inst-cnes-3876500", "CMA SERVICOS MEDICOS HOSPITALARES LTDA"], ["org-isol-inst-cnes-4000153", "VIVA ANESTESIA SERVICOS MEDICOS HOSPITALARES LTDA"], ["org-isol-inst-cnes-4127897", "ORTOSURG SERVICOS ODONTO HOSPITALARES LTDA"], ["org-isol-inst-cnes-4441788", "SBB SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-4479319", "MASSUCCI E BISSOLI HOSPITALAR LTDA"], ["org-isol-inst-cnes-4630416", "SES MEDICAL PRODUTOS MEDICOS HOSPITALARES LTDA"], ["org-isol-inst-cnes-4754778", "K DANTAS SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-4754832", "LIMA DE QUEIROZ SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-4848691", "LUCENA E SILVA SERVICOS MEDICOS HOSPITALARES LTDA"], ["org-isol-inst-cnes-4868315", "SEGEL SERVICOS MEDICOS HOSPITALARES LTDA"], ["org-isol-inst-cnes-4876180", "SHINICHI SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-4922875", "SER CLINICA DE ANESTESIA E SERVICOS MEDICOS HOSPITALARES LTD"], ["org-isol-inst-cnes-4946871", "MARCAL SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-4994086", "SANTA SARA SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-5361567", "SMX HOSPITALAR LTDA"], ["org-isol-inst-cnes-5501237", "R CEC CONSULTORIA E GESTAO HOSPITALAR LTDA"], ["org-isol-inst-cnes-5614414", "LOGOS ASSISTENCIA MEDICA E HOSPITALAR LTDA"], ["org-isol-inst-cnes-5758548", "NEW DAY HOSPITAL LTDA"], ["org-isol-inst-cnes-5811236", "MEDINA SERVICOS MEDICOS E HOSPITALARES LTDA ME"], ["org-isol-inst-cnes-7120303", "LIFECARE ASSISTENCIA MEDICA DOMICILIAR E HOSPITALAR LTDA"], ["org-isol-inst-cnes-7120362", "SERVICOS MEDICOS HOSPITALARES SANTA RITA LTDA"], ["org-isol-inst-cnes-7164629", "SANTA ISABELLA SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-7231032", "SERV SOCIAL DA IND DO PAPEL PAPELAO E CORT DO EST DE SP"], ["org-isol-inst-cnes-7266472", "OSL SERVICOS MEDICOS HOSPITALARES LTDA EPP"], ["org-isol-inst-cnes-75426", "SISTEMAS E PLANOS DE SAUDE LTDA"], ["org-isol-inst-cnes-7602227", "MEJI ASSISTENCIA MEDICA LTDA"], ["org-isol-inst-cnes-7794924", "TAMP SERVICOS MEDICOS HOSPITALAR LTDA EPP"], ["org-isol-inst-cnes-795402", "KRBR SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-803626", "CEMA HOSPITAL ESPECIALIZADO MORUMBI"], ["org-isol-inst-cnes-8373027", "UJD SERVICOS MEDICOS E HOSPITALARES LTDA"], ["org-isol-inst-cnes-853968", "RP CONSULTORIA MEDICA E HOSPITALAR LTDA"], ["org-isol-inst-cnes-9234195", "YL ODONTOLOGIA ESPECIALIZADA EIRELI ME"], ["org-isol-inst-cnes-9274111", "SERVICO DE HEMOTERAPIA MADRE REGINA LTDA"], ["org-isol-inst-cnes-9612076", "NESPAH NUCLEO ESPECIALIZADO EM ANESTESIOLOGIA HOSPITALAR LT"], ["org-isol-inst-cnes-9646019", "HOSPITAL DA PELE LTDA"], ["org-isol-inst-cnes-9712615", "SCARPARO SCOPIA CONSULTORIA MEDICA LTDA"], ["org-isol-inst-cnes-9873244", "LM ODONTOLOGIA ESPECIALIZADA EIRELI"],
  ] as [string, string][]).map(([grupoEconomicoId, nome]) => ({ grupoEconomicoId, dataPesquisa: "2026-09-05T00:00:00.000Z", termosConsulta: [`${nome} compras OR suprimentos OR administrativo`], fontesConsultadas: [], resultado: "Nenhum contato foi aceito: a pesquisa pÃºblica documentada nÃ£o localizou perfil individual verificÃ¡vel com vÃ­nculo atual e cargo-alvo corporativo.", confianca: "ALTA" as NivelConfianca, status: "SEM_CONTATO_VERIFICAVEL" as StatusPesquisaContato, statusRevisao: "APROVADA" as StatusRevisao })),
];

async function main() {
  for (const pesquisa of pesquisas) {
    const grupo = await prisma.grupoEconomico.findFirst({
      where: {
        id: pesquisa.grupoEconomicoId,
        natureza: "PRIVADO",
        instituicoes: { some: { tipoDado: "FATO_OFICIAL", segmentacao: { segmento: "NUCLEO_HOSPITALAR" } } },
      },
      select: { id: true },
    });
    if (!grupo) throw new Error(`OrganizaÃ§Ã£o fora do escopo: ${pesquisa.grupoEconomicoId}`);
    await prisma.pesquisaContatoOrganizacao.upsert({
      where: { grupoEconomicoId: grupo.id },
      update: { ...pesquisa, dataPesquisa: new Date(pesquisa.dataPesquisa), termosConsulta: JSON.stringify(pesquisa.termosConsulta), fontesConsultadas: JSON.stringify(pesquisa.fontesConsultadas) },
      create: { id: `pesquisa-contato-${grupo.id}`, ...pesquisa, dataPesquisa: new Date(pesquisa.dataPesquisa), termosConsulta: JSON.stringify(pesquisa.termosConsulta), fontesConsultadas: JSON.stringify(pesquisa.fontesConsultadas) },
    });
  }
  console.log(JSON.stringify({ processadas: pesquisas.length, semContatoVerificavel: pesquisas.filter((pesquisa) => pesquisa.status === "SEM_CONTATO_VERIFICAVEL").length }, null, 2));
}

main().catch((erro) => { console.error(erro); process.exitCode = 1; }).finally(() => prisma.$disconnect());

