import { CheckCircle2, Database, FileCheck2, Scale, ShieldAlert } from "lucide-react";
import { CabecalhoPagina } from "@/components/cabecalho-pagina";
import { MarcadorTipo } from "@/components/rotulos";
import { PESOS_INDICE, ROTULOS_CRITERIOS, type CriterioIndice } from "@/domain/indice/pesos";
import type { TipoDado } from "@/domain/tipos";
import { obterModoDados } from "@/domain/modo-dados";

const categorias: Array<{ tipo: TipoDado; descricao: string }> = [
  { tipo: "FATO_OFICIAL", descricao: "Informação emitida por órgão ou base oficial identificável." },
  { tipo: "FATO_PUBLICO", descricao: "Informação publicamente verificável em fonte identificada." },
  { tipo: "INFERENCIA", descricao: "Conclusão derivada de fatos, sempre apresentada com sua justificativa." },
  { tipo: "HIPOTESE", descricao: "Possibilidade que ainda exige validação antes de orientar uma decisão." },
  { tipo: "DEMONSTRACAO", descricao: "Conteúdo fictício criado somente para testar a aplicação." },
];

export default function GovernancaPage() {
  const modo = obterModoDados();
  return <div className="w-full px-3 py-5 sm:px-6 lg:px-8 lg:py-8 2xl:px-10"><CabecalhoPagina titulo="Governança de Dados" descricao="Regras para preservar origem, confiança, revisão e distinção clara entre fato, inferência, hipótese e demonstração." />
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><article className="painel p-6"><div className="flex items-center gap-3"><Scale className="text-[var(--azul)]" size={22} /><h2 className="text-lg font-bold">Categorias canônicas</h2></div><div className="mt-5 space-y-3">{categorias.map((item) => <div className="rounded-xl border border-[var(--borda)] p-4" key={item.tipo}><MarcadorTipo tipo={item.tipo} /><p className="mt-2 text-sm leading-6 text-[var(--texto-suave)]">{item.descricao}</p></div>)}</div></article><div className="space-y-6"><article className="painel p-6"><div className="flex items-center gap-3"><FileCheck2 className="text-[var(--sucesso)]" size={22} /><h2 className="text-lg font-bold">Confiança e revisão</h2></div><dl className="mt-5 space-y-4 text-sm"><div><dt className="font-bold text-emerald-700">Alta</dt><dd className="mt-1 text-[var(--texto-suave)]">Fonte identificada, informação consistente e revisão concluída.</dd></div><div><dt className="font-bold text-amber-700">Média</dt><dd className="mt-1 text-[var(--texto-suave)]">Informação útil, mas que ainda merece confirmação adicional.</dd></div><div><dt className="font-bold text-rose-700">Baixa</dt><dd className="mt-1 text-[var(--texto-suave)]">Não deve sustentar abordagem comercial sem reforço.</dd></div></dl></article><article className="painel border-l-4 border-l-amber-400 p-6"><div className="flex gap-3"><ShieldAlert className="mt-0.5 shrink-0 text-amber-700" size={21} /><div><h2 className="font-bold">Regra do Gate 1</h2><p className="mt-2 text-sm leading-6 text-[var(--texto-suave)]">{modo === "MODO_DEMONSTRACAO" ? "Modo demonstração ativo: a interface exibe somente registros fictícios identificados como DEMONSTRAÇÃO." : "MODO REAL ativo: a interface exibe somente registros FATO OFICIAL, preservando a distinção entre fato, inferência, hipótese e demonstração."}</p></div></div></article></div></section>
    <section className="painel mt-6 overflow-hidden"><div className="border-b border-[var(--borda)] px-6 py-5"><h2 className="text-lg font-bold">Pesos do Índice de Prioridade Hospitalar</h2><p className="mt-1 text-sm text-[var(--texto-suave)]">Configuração versão 1.0.0, separada da lógica de cálculo. Total máximo: 100 pontos.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-50 text-[var(--texto-suave)]"><tr><th className="px-6 py-3">Critério</th><th className="px-4 py-3">Peso máximo</th></tr></thead><tbody>{(Object.keys(PESOS_INDICE) as CriterioIndice[]).map((criterio) => <tr className="border-t border-[var(--borda)]" key={criterio}><td className="px-6 py-3 font-medium">{ROTULOS_CRITERIOS[criterio]}</td><td className="px-4 py-3 font-bold text-[var(--azul)]">{PESOS_INDICE[criterio]}</td></tr>)}</tbody><tfoot><tr className="border-t-2 border-[var(--azul)] bg-slate-50"><th className="px-6 py-4">Total</th><th className="px-4 py-4">100</th></tr></tfoot></table></div></section>
    <section className="painel mt-6 p-6"><div className="flex items-center gap-3"><Database className="text-[var(--azul)]" size={22} /><h2 className="text-lg font-bold">Fluxo futuro de publicação</h2></div><ol className="mt-6 grid gap-3 md:grid-cols-4 xl:grid-cols-7">{["Coleta", "Normalização", "Resolução de entidade", "Validação", "Evidência", "Índice", "Publicação"].map((etapa, indice) => <li className="relative rounded-xl bg-slate-50 p-4 text-sm font-bold" key={etapa}><span className="mb-2 block text-xs text-[var(--azul)]">{String(indice + 1).padStart(2, "0")}</span>{etapa}</li>)}</ol><p className="mt-5 flex gap-2 text-sm leading-6 text-[var(--texto-suave)]"><CheckCircle2 className="mt-0.5 shrink-0 text-[var(--sucesso)]" size={18} />Agentes futuros podem apoiar análise e síntese, mas nunca substituem os dados estruturados e as evidências como fonte primária da verdade.</p></section>
  </div>;
}
